### ISSUE TITLE
bazel-0.27 issue

### ISSUE THREAD

**Issue by soonho-tri** [dreal/dreal4#143]
need to fix python part.

```
❯ ./bazel-bin/dreal/api_test_py                                                                                                                                    
Traceback (most recent call last):
  File "/home/soonhok/work/dreal4/./bazel-bin/dreal/api_test_py.runfiles/dreal/dreal/test/python/api_test.py", line 7, in <module>
    from dreal import *
  File "/home/soonhok/work/dreal4/bazel-bin/dreal/api_test_py.runfiles/dreal/dreal/__init__.py", line 7, in <module>
    from dreal._dreal_py import *
ImportError: /home/soonhok/work/dreal4/bazel-bin/dreal/api_test_py.runfiles/dreal/dreal/_dreal_py.so: undefined symbol: _Py_ZeroStruct
```

**Comment by soonho-tri** [comment]
Close by 7d6893eeae3d27ffb9efa75d82e404413543f38b, e3cb55a355a6e035ddc2bc62b0a1b3e09c26c38e, 78c5814e0c7eafd83d3b09fdfdd88ae4db132f3d
