### ISSUE TITLE
ASAN memory leak when parsing error

### ISSUE THREAD

**Issue by rainoftime** [dreal/dreal4#172]
Hi, for the following instance, asan detects a memory leak in dreal4 (Commit 078027483556)

~~~~
(set-logic QF_NRA)
(declare-const v0 Bool)
(declare-const v1 Bool)
(declare-const v2 Bool)
(declare-const v3 Bool)
(declare-const v4 Bool)
(declare-const v5 Bool)
(declare-const v6 Bool)
(declare-const v7 Bool)
(declare-const v8 Bool)
(declare-const v9 Bool)
(declare-const v10 Bool)
(declare-const v11 Bool)
(declare-const v12 Bool)
(declare-const v13 Bool)
(declare-const v14 Bool)
(declare-const v15 Bool)
(declare-const v16 Bool)
(declare-const v17 Bool)
(declare-const v18 Bool)
(declare-const r0 Real)
(declare-const r1 Real)
(declare-const r7 Real)
(declare-const r9 Real)
(declare-const r11 Real)
(assert (or (and v2 v12 v6 v13 v12 v7 v1 v11 v14 v6) v3 v6 (and v2 v12 v6 v13 v12 v7 v1 v11 v14 v6) v1 v3))
(assert (and v4 v4 v13 v16 v11 v0 v12))
(declare-const v19 Bool)
(declare-const v20 Bool)
(assert (= v15 (or (and v2 v12 v6 v13 v12 v7 v1 v11 v14 v6) v3 v6 (and v2 v12 v6 v13 v12 v7 v1 v11 v14 v6) v1 v3)))
(declare-const v21 Bool)
(assert v3)
(declare-const v22 Bool)
(assert v20)
(assert (not v1))
(declare-const v23 Bool)
(assert (and v7 v8 (and v2 v12 v6 v13 v12 v7 v1 v11 v14 v6) (not v1) (and v2 v12 v6 v13 v12 v7 v1 v11 v14 v6) (>= r9 r9 r11) v9 v1 v21))
(declare-const r12 Real)
(declare-const v24 Bool)
(declare-const r13 Real)
(declare-const v25 Bool)
(declare-const r14 Real)
(assert (or (= v12 v10 v13 v1 v9 v16 v10 v8) (= v12 v10 v13 v1 v9 v16 v10 v8) v17 (and v2 v12 v6 v13 v12 v7 v1 v11 v14 v6) (= v12 v10 v13 v1 v9 v16 v10 v8) (= v15 (or (and v2 v12 v6 v13 v12 v7 v1 v11 v14 v6) v3 v6 (and v2 v12 v6 v13 v12 v7 v1 v11 v14 v6) v1 v3)) (= v4 v24 v16 (or (and v2 v12 v6 v13 v12 v7 v1 v11 v14 v6) v3 v6 (and v2 v12 v6 v13 v12 v7 v1 v11 v14 v6) v1 v3) v14 (and v7 v8 (and v2 v12 v6 v13 v12 v7 v1 v11 v14 v6) (not v1) (and v2 v12 v6 v13 v12 v7 v1 v11 v14 v6) (>= r9 r9 r11) v9 v1 v21) (<= 709257 82141) (= v12 v10 v13 v1 v9 v16 v10 v8)) v8))
(declare-const v26 Bool)
(assert v16)
(assert v14)
(declare-const v27 Bool)
(assert (=> (and v14 (and v4 v4 v13 v16 v11 v0 v12) v7 (>= 7 r7) v3 v2 v1) v14))
(assert (<= r13 174 r0 207549.772))
(declare-const v28 Bool)
(declare-const r15 Real)
(assert v17)
(declare-const v29 Bool)
(declare-const v30 Bool)
(declare-const r16 Real)
(assert (not v9))
(declare-const v31 Bool)
(declare-const v32 Bool)
(declare-const v33 Bool)
(assert (= (>= 617 (/ 7 480) (- (- 0.02197696)) r9) (or (= v12 v10 v13 v1 v9 v16 v10 v8) (= v12 v10 v13 v1 v9 v16 v10 v8) v17 (and v2 v12 v6 v13 v12 v7 v1 v11 v14 v6) (= v12 v10 v13 v1 v9 v16 v10 v8) (= v15 (or (and v2 v12 v6 v13 v12 v7 v1 v11 v14 v6) v3 v6 (and v2 v12 v6 v13 v12 v7 v1 v11 v14 v6) v1 v3)) (= v4 v24 v16 (or (and v2 v12 v6 v13 v12 v7 v1 v11 v14 v6) v3 v6 (and v2 v12 v6 v13 v12 v7 v1 v11 v14 v6) v1 v3) v14 (and v7 v8 (and v2 v12 v6 v13 v12 v7 v1 v11 v14 v6) (not v1) (and v2 v12 v6 v13 v12 v7 v1 v11 v14 v6) (>= r9 r9 r11) v9 v1 v21) (<= 709257 82141) (= v12 v10 v13 v1 v9 v16 v10 v8)) v8) (< r11 5243.0)))
(declare-const v34 Bool)
(assert (> r15 (+ (/ 7 480) 22163) 36.34629279 5243.0))
(assert (or (or (= v12 v10 v13 v1 v9 v16 v10 v8) (= v12 v10 v13 v1 v9 v16 v10 v8) v17 (and v2 v12 v6 v13 v12 v7 v1 v11 v14 v6) (= v12 v10 v13 v1 v9 v16 v10 v8) (= v15 (or (and v2 v12 v6 v13 v12 v7 v1 v11 v14 v6) v3 v6 (and v2 v12 v6 v13 v12 v7 v1 v11 v14 v6) v1 v3)) (= v4 v24 v16 (or (and v2 v12 v6 v13 v12 v7 v1 v11 v14 v6) v3 v6 (and v2 v12 v6 v13 v12 v7 v1 v11 v14 v6) v1 v3) v14 (and v7 v8 (and v2 v12 v6 v13 v12 v7 v1 v11 v14 v6) (not v1) (and v2 v12 v6 v13 v12 v7 v1 v11 v14 v6) (>= r9 r9 r11) v9 v1 v21) (<= 709257 82141) (= v12 v10 v13 v1 v9 v16 v10 v8)) v8) v14 v24 v33 (>= r9 r9 r11) v5 v12))
(assert v27)
(check-sat)
~~~~

~~~~
/tmp/drealtest1/dreal31.smt2:37.121-122 : syntax error, unexpected symbol, expecting ')'

=================================================================
==33793==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 48 byte(s) in 2 object(s) allocated from:
    #0 0x7f343d871532 in operator new(unsigned long) (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x99532)
    #1 0x55778978aa53 in dreal::Smt2Parser::parse() dreal/smt2/parser.yy:392
    #2 0x557789782e33 in dreal::Smt2Driver::parse_stream(std::istream&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator
<char> > const&) dreal/smt2/driver.cc:36
    #3 0x557789783163 in dreal::Smt2Driver::parse_file(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) 
dreal/smt2/driver.cc:48
    #4 0x5577897854d4 in dreal::RunSmt2(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, dreal::Config c
onst&, bool, bool) dreal/smt2/run.cc:21
    #5 0x55778965efa6 in dreal::MainProgram::Run() dreal/dreal_main.cc:412
~~~~

**Comment by soonho-tri** [comment]
Closed by #179
