### ISSUE TITLE
heap-buffer-overflow at ibex_mistral_Bitset.h:204

### ISSUE THREAD

**Issue by rainoftime** [dreal/dreal4#181]
Hi, for the following instance, asan detects a uaf in dreal4 (Commit 078027
~~~~
(set-logic QF_NRA)
(assert (forall ((q0 Real) (q1 Real) (q2 Bool) (q3 Bool)) q3))
(check-sat)
~~~~

~~~~
==29995==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60200000e8cc at pc 0x5652f816dd18 bp 0x7ffca5fa8720 sp 0x7ffca5fa8710
READ of size 4 at 0x60200000e8cc thread T0
    #0 0x5652f816dd17 in Mistral::Bitset<unsigned int, float>::initialise(int, int, unsigned int, unsigned int*) external/ibex/include/_opt_lib
ibex_2.7.4_include_ibex/ibex_mistral_Bitset.h:204
    #1 0x5652f815eb9e in Mistral::Bitset<unsigned int, float>::Bitset(int, int, unsigned int) external/ibex/include/_opt_libibex_2.7.4_include_
ibex/ibex_mistral_Bitset.h:160
    #2 0x5652f814f12a in ibex::BitSet::BitSet(int) external/ibex/include/_opt_libibex_2.7.4_include_ibex/ibex_BitSet.h:264
    #3 0x5652f82fe0e1 in ibex::BitSet::empty(int) external/ibex/include/_opt_libibex_2.7.4_include_ibex/ibex_BitSet.h:270
    #4 0x5652f8398a3e in dreal::ContractorStatus::ContractorStatus(dreal::Box, int) dreal/contractor/contractor_status.cc:58
    #5 0x5652f82fd6a0 in dreal::TheorySolver::CheckSat(dreal::Box const&, std::vector<dreal::drake::symbolic::Formula, std::allocator<dreal::dr
ake::symbolic::Formula> > const&) dreal/solver/theory_solver.cc:191
    #6 0x5652f829420c in dreal::Context::Impl::CheckSatCore(dreal::ScopedVector<dreal::drake::symbolic::Formula> const&, dreal::Box, dreal::Sat
Solver*) dreal/solver/context_impl.cc:156
    #7 0x5652f82946e2 in dreal::Context::Impl::CheckSat() dreal/solver/context_impl.cc:184
    #8 0x5652f828d969 in dreal::Context::CheckSat() dreal/solver/context.cc:27
    #9 0x5652f826160d in dreal::Smt2Driver::CheckSat() dreal/smt2/driver.cc:63
    #10 0x5652f82654cf in dreal::Smt2Parser::parse() dreal/smt2/parser.yy:160
    #11 0x5652f8260e33 in dreal::Smt2Driver::parse_stream(std::istream&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocato
r<char> > const&) dreal/smt2/driver.cc:36
    #12 0x5652f8261163 in dreal::Smt2Driver::parse_file(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
 dreal/smt2/driver.cc:48
    #13 0x5652f82634d4 in dreal::RunSmt2(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, dreal::Config 
const&, bool, bool) dreal/smt2/run.cc:21
    #14 0x5652f813cfa6 in dreal::MainProgram::Run() dreal/dreal_main.cc:412
    #15 0x5652f813d30b in main dreal/dreal_main.cc:437
    #16 0x7fbd59cf582f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #17 0x5652f81378e8 in _start (/home/rainoftime/.cache/bazel/_bazel_rainoftime/6bee3a30a62c06868a2fc9a1ea1e3ee7/execroot/dreal/bazel-out/k8-
dbg/bin/dreal/dreal+0xee8e8)
~~~~

Perhaps in dreal, we cannot use Boolean variables in quantified formulas?

**Comment by soonho-tri** [comment]
Fixed by #215
