### ISSUE TITLE
Segment fault at ibex_mistral_Bitset.h:461 (--worklist-fixpoint --jobs 2)

### ISSUE THREAD

**Issue by rainoftime** [dreal/dreal4#194]
Hi, for the following formula,
~~~~
(set-logic QF_NRA)
(declare-fun _substvar_261_ () Bool)
(declare-const v13 Bool)
(declare-const r6 Real)
(declare-const r9 Real)
(assert (or (and v13 (or v13 (= r6 r9))) _substvar_261_))
(check-sat)
~~~~
dreal 662723e throws a seg fault

~~~~
=================================================================                                                                    [184/1923]
==45130==ERROR: AddressSanitizer: SEGV on unknown address 0x60201000154c (pc 0x5603c22de38c bp 0x7f73fe8fca60 sp 0x7f73fe8fca50 T1)
==45130==The signal is caused by a READ memory access.
    #0 0x5603c22de38b in Mistral::Bitset<unsigned int, float>::fast_remove(int) external/ibex/include/_opt_libibex_2.7.4_include_ibex/ibex_mist
ral_Bitset.h:461
    #1 0x5603c22de25d in ibex::BitSet::remove(int) external/ibex/include/_opt_libibex_2.7.4_include_ibex/ibex_BitSet.h:316
    #2 0x5603c22dcfa4 in dreal::ContractorWorklistFixpoint::Prune(dreal::ContractorStatus*) const dreal/contractor/contractor_worklist_fixpoint
.cc:121
    #3 0x5603c22a79b5 in dreal::Contractor::Prune(dreal::ContractorStatus*) const dreal/contractor/contractor.cc:93
    #4 0x5603c21ec8b9 in Worker dreal/solver/icp_parallel.cc:95
    #5 0x5603c220d5e3 in void std::__invoke_impl<void, void (*&)(dreal::Contractor const&, dreal::Config const&, std::vector<dreal::FormulaEval
uator, std::allocator<dreal::FormulaEvaluator> > const&, int, bool, cds::container::TreiberStack<cds::gc::HP, dreal::Box, cds::container::treib
er_stack::traits>*, dreal::ContractorStatus*, std::atomic<int>*, std::atomic<int>*), dreal::Contractor&, dreal::Config&, std::vector<dreal::For
mulaEvaluator, std::allocator<dreal::FormulaEvaluator> >&, int&, bool&, cds::container::TreiberStack<cds::gc::HP, dreal::Box, cds::container::t
reiber_stack::traits>*&, dreal::ContractorStatus*&, std::atomic<int>*&, std::atomic<int>*&>(std::__invoke_other, void (*&)(dreal::Contractor co
nst&, dreal::Config const&, std::vector<dreal::FormulaEvaluator, std::allocator<dreal::FormulaEvaluator> > const&, int, bool, cds::container::T
reiberStack<cds::gc::HP, dreal::Box, cds::container::treiber_stack::traits>*, dreal::ContractorStatus*, std::atomic<int>*, std::atomic<int>*), 
dreal::Contractor&, dreal::Config&, std::vector<dreal::FormulaEvaluator, std::allocator<dreal::FormulaEvaluator> >&, int&, bool&, cds::containe
r::TreiberStack<cds::gc::HP, dreal::Box, cds::container::treiber_stack::traits>*&, dreal::ContractorStatus*&, std::atomic<int>*&, std::atomic<i
nt>*&) /usr/include/c++/7/bits/invoke.h:60
    #6 0x5603c220d2a7 in std::__invoke_result<void (*&)(dreal::Contractor const&, dreal::Config const&, std::vector<dreal::FormulaEva[164/1923]
d::allocator<dreal::FormulaEvaluator> > const&, int, bool, cds::container::TreiberStack<cds::gc::HP, dreal::Box, cds::container::treiber_stack:
:traits>*, dreal::ContractorStatus*, std::atomic<int>*, std::atomic<int>*), dreal::Contractor&, dreal::Config&, std::vector<dreal::FormulaEvalu
ator, std::allocator<dreal::FormulaEvaluator> >&, int&, bool&, cds::container::TreiberStack<cds::gc::HP, dreal::Box, cds::container::treiber_st
ack::traits>*&, dreal::ContractorStatus*&, std::atomic<int>*&, std::atomic<int>*&>::type std::__invoke<void (*&)(dreal::Contractor const&, drea
l::Config const&, std::vector<dreal::FormulaEvaluator, std::allocator<dreal::FormulaEvaluator> > const&, int, bool, cds::container::TreiberStac
k<cds::gc::HP, dreal::Box, cds::container::treiber_stack::traits>*, dreal::ContractorStatus*, std::atomic<int>*, std::atomic<int>*), dreal::Con
tractor&, dreal::Config&, std::vector<dreal::FormulaEvaluator, std::allocator<dreal::FormulaEvaluator> >&, int&, bool&, cds::container::Treiber
Stack<cds::gc::HP, dreal::Box, cds::container::treiber_stack::traits>*&, dreal::ContractorStatus*&, std::atomic<int>*&, std::atomic<int>*&>(voi
d (*&)(dreal::Contractor const&, dreal::Config const&, std::vector<dreal::FormulaEvaluator, std::allocator<dreal::FormulaEvaluator> > const&, i
nt, bool, cds::container::TreiberStack<cds::gc::HP, dreal::Box, cds::container::treiber_stack::traits>*, dreal::ContractorStatus*, std::atomic<
int>*, std::atomic<int>*), dreal::Contractor&, dreal::Config&, std::vector<dreal::FormulaEvaluator, std::allocator<dreal::FormulaEvaluator> >&,
 int&, bool&, cds::container::TreiberStack<cds::gc::HP, dreal::Box, cds::container::treiber_stack::traits>*&, dreal::ContractorStatus*&, std::a
tomic<int>*&, std::atomic<int>*&) /usr/include/c++/7/bits/invoke.h:95
    #7 0x5603c220cd4c in void std::_Bind<void (*(dreal::Contractor, dreal::Config, std::vector<dreal::FormulaEvaluator, std::allocator<dreal::F
ormulaEvaluator> >, int, bool, cds::container::TreiberStack<cds::gc::HP, dreal::Box, cds::container::treiber_stack::traits>*, dreal::Contractor
Status*, std::atomic<int>*, std::atomic<int>*))(dreal::Contractor const&, dreal::Config const&, std::vector<dreal::FormulaEvaluator, std::alloc
ator<dreal::FormulaEvaluator> > const&, int, bool, cds::container::TreiberStack<cds::gc::HP, dreal::Box, cds::container::treiber_stack::traits>
*, dreal::ContractorStatus*, std::atomic<int>*, std::atomic<int>*)>::__call<void, , 0ul, 1ul, 2ul, 3ul, 4ul, 5ul, 6ul, 7ul, 8ul>(std::tuple<>&&
, std::_Index_tuple<0ul, 1ul, 2ul, 3ul, 4ul, 5ul, 6ul, 7ul, 8ul>) /usr/include/c++/7/functional:467
    #8 0x5603c220c177 in void std::_Bind<void (*(dreal::Contractor, dreal::Config, std::vector<dreal::FormulaEvaluator, std::allocato[144/1923]
ormulaEvaluator> >, int, bool, cds::container::TreiberStack<cds::gc::HP, dreal::Box, cds::container::treiber_stack::traits>*, dreal::Contractor
Status*, std::atomic<int>*, std::atomic<int>*))(dreal::Contractor const&, dreal::Config const&, std::vector<dreal::FormulaEvaluator, std::alloc
ator<dreal::FormulaEvaluator> > const&, int, bool, cds::container::TreiberStack<cds::gc::HP, dreal::Box, cds::container::treiber_stack::traits>
*, dreal::ContractorStatus*, std::atomic<int>*, std::atomic<int>*)>::operator()<, void>() /usr/include/c++/7/functional:551
    #9 0x5603c220b7f0 in void std::__invoke_impl<void, std::_Bind<void (*(dreal::Contractor, dreal::Config, std::vector<dreal::FormulaEvaluator
, std::allocator<dreal::FormulaEvaluator> >, int, bool, cds::container::TreiberStack<cds::gc::HP, dreal::Box, cds::container::treiber_stack::tr
aits>*, dreal::ContractorStatus*, std::atomic<int>*, std::atomic<int>*))(dreal::Contractor const&, dreal::Config const&, std::vector<dreal::For
mulaEvaluator, std::allocator<dreal::FormulaEvaluator> > const&, int, bool, cds::container::TreiberStack<cds::gc::HP, dreal::Box, cds::containe
r::treiber_stack::traits>*, dreal::ContractorStatus*, std::atomic<int>*, std::atomic<int>*)>&>(std::__invoke_other, std::_Bind<void (*(dreal::C
ontractor, dreal::Config, std::vector<dreal::FormulaEvaluator, std::allocator<dreal::FormulaEvaluator> >, int, bool, cds::container::TreiberSta
ck<cds::gc::HP, dreal::Box, cds::container::treiber_stack::traits>*, dreal::ContractorStatus*, std::atomic<int>*, std::atomic<int>*))(dreal::Co
ntractor const&, dreal::Config const&, std::vector<dreal::FormulaEvaluator, std::allocator<dreal::FormulaEvaluator> > const&, int, bool, cds::c
ontainer::TreiberStack<cds::gc::HP, dreal::Box, cds::container::treiber_stack::traits>*, dreal::ContractorStatus*, std::atomic<int>*, std::atom
ic<int>*)>&) /usr/include/c++/7/bits/invoke.h:60
    #10 0x5603c220b380 in std::__invoke_result<std::_Bind<void (*(dreal::Contractor, dreal::Config, std::vector<dreal::FormulaEvaluator, std::a
llocator<dreal::FormulaEvaluator> >, int, bool, cds::container::TreiberStack<cds::gc::HP, dreal::Box, cds::container::treiber_stack::traits>*, 
dreal::ContractorStatus*, std::atomic<int>*, std::atomic<int>*))(dreal::Contractor const&, dreal::Config const&, std::vector<dreal::FormulaEval
uator, std::allocator<dreal::FormulaEvaluator> > const&, int, bool, cds::container::TreiberStack<cds::gc::HP, dreal::Box, cds::container::treib
er_stack::traits>*, dreal::ContractorStatus*, std::atomic<int>*, std::atomic<int>*)>&>::type std::__invoke<std::_Bind<void (*(dreal::Contractor

**Comment by soonho-tri** [comment]
Thanks for the report. I'm working on a fix. Subscribe #195 for a follow up.
